# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/PROGRAM/cpp/db

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/PROGRAM/cpp/db

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /mnt/d/PROGRAM/cpp/db/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/PROGRAM/cpp/db/CMakeFiles /mnt/d/PROGRAM/cpp/db/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/PROGRAM/cpp/db/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named minisql

# Build rule for target.
minisql: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 minisql
.PHONY : minisql

# fast build rule for target.
minisql/fast:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/build
.PHONY : minisql/fast

src/API.o: src/API.cpp.o

.PHONY : src/API.o

# target to build an object file
src/API.cpp.o:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/API.cpp.o
.PHONY : src/API.cpp.o

src/API.i: src/API.cpp.i

.PHONY : src/API.i

# target to preprocess a source file
src/API.cpp.i:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/API.cpp.i
.PHONY : src/API.cpp.i

src/API.s: src/API.cpp.s

.PHONY : src/API.s

# target to generate assembly for a file
src/API.cpp.s:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/API.cpp.s
.PHONY : src/API.cpp.s

src/Block.o: src/Block.cpp.o

.PHONY : src/Block.o

# target to build an object file
src/Block.cpp.o:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/Block.cpp.o
.PHONY : src/Block.cpp.o

src/Block.i: src/Block.cpp.i

.PHONY : src/Block.i

# target to preprocess a source file
src/Block.cpp.i:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/Block.cpp.i
.PHONY : src/Block.cpp.i

src/Block.s: src/Block.cpp.s

.PHONY : src/Block.s

# target to generate assembly for a file
src/Block.cpp.s:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/Block.cpp.s
.PHONY : src/Block.cpp.s

src/CatalogManager.o: src/CatalogManager.cpp.o

.PHONY : src/CatalogManager.o

# target to build an object file
src/CatalogManager.cpp.o:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/CatalogManager.cpp.o
.PHONY : src/CatalogManager.cpp.o

src/CatalogManager.i: src/CatalogManager.cpp.i

.PHONY : src/CatalogManager.i

# target to preprocess a source file
src/CatalogManager.cpp.i:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/CatalogManager.cpp.i
.PHONY : src/CatalogManager.cpp.i

src/CatalogManager.s: src/CatalogManager.cpp.s

.PHONY : src/CatalogManager.s

# target to generate assembly for a file
src/CatalogManager.cpp.s:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/CatalogManager.cpp.s
.PHONY : src/CatalogManager.cpp.s

src/File.o: src/File.cpp.o

.PHONY : src/File.o

# target to build an object file
src/File.cpp.o:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/File.cpp.o
.PHONY : src/File.cpp.o

src/File.i: src/File.cpp.i

.PHONY : src/File.i

# target to preprocess a source file
src/File.cpp.i:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/File.cpp.i
.PHONY : src/File.cpp.i

src/File.s: src/File.cpp.s

.PHONY : src/File.s

# target to generate assembly for a file
src/File.cpp.s:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/File.cpp.s
.PHONY : src/File.cpp.s

src/IndexManager.o: src/IndexManager.cpp.o

.PHONY : src/IndexManager.o

# target to build an object file
src/IndexManager.cpp.o:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/IndexManager.cpp.o
.PHONY : src/IndexManager.cpp.o

src/IndexManager.i: src/IndexManager.cpp.i

.PHONY : src/IndexManager.i

# target to preprocess a source file
src/IndexManager.cpp.i:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/IndexManager.cpp.i
.PHONY : src/IndexManager.cpp.i

src/IndexManager.s: src/IndexManager.cpp.s

.PHONY : src/IndexManager.s

# target to generate assembly for a file
src/IndexManager.cpp.s:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/IndexManager.cpp.s
.PHONY : src/IndexManager.cpp.s

src/RecordManager.o: src/RecordManager.cpp.o

.PHONY : src/RecordManager.o

# target to build an object file
src/RecordManager.cpp.o:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/RecordManager.cpp.o
.PHONY : src/RecordManager.cpp.o

src/RecordManager.i: src/RecordManager.cpp.i

.PHONY : src/RecordManager.i

# target to preprocess a source file
src/RecordManager.cpp.i:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/RecordManager.cpp.i
.PHONY : src/RecordManager.cpp.i

src/RecordManager.s: src/RecordManager.cpp.s

.PHONY : src/RecordManager.s

# target to generate assembly for a file
src/RecordManager.cpp.s:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/RecordManager.cpp.s
.PHONY : src/RecordManager.cpp.s

src/buffermanager.o: src/buffermanager.cpp.o

.PHONY : src/buffermanager.o

# target to build an object file
src/buffermanager.cpp.o:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/buffermanager.cpp.o
.PHONY : src/buffermanager.cpp.o

src/buffermanager.i: src/buffermanager.cpp.i

.PHONY : src/buffermanager.i

# target to preprocess a source file
src/buffermanager.cpp.i:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/buffermanager.cpp.i
.PHONY : src/buffermanager.cpp.i

src/buffermanager.s: src/buffermanager.cpp.s

.PHONY : src/buffermanager.s

# target to generate assembly for a file
src/buffermanager.cpp.s:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/buffermanager.cpp.s
.PHONY : src/buffermanager.cpp.s

src/interpreter.o: src/interpreter.cpp.o

.PHONY : src/interpreter.o

# target to build an object file
src/interpreter.cpp.o:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/interpreter.cpp.o
.PHONY : src/interpreter.cpp.o

src/interpreter.i: src/interpreter.cpp.i

.PHONY : src/interpreter.i

# target to preprocess a source file
src/interpreter.cpp.i:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/interpreter.cpp.i
.PHONY : src/interpreter.cpp.i

src/interpreter.s: src/interpreter.cpp.s

.PHONY : src/interpreter.s

# target to generate assembly for a file
src/interpreter.cpp.s:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/interpreter.cpp.s
.PHONY : src/interpreter.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/table.o: src/table.cpp.o

.PHONY : src/table.o

# target to build an object file
src/table.cpp.o:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/table.cpp.o
.PHONY : src/table.cpp.o

src/table.i: src/table.cpp.i

.PHONY : src/table.i

# target to preprocess a source file
src/table.cpp.i:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/table.cpp.i
.PHONY : src/table.cpp.i

src/table.s: src/table.cpp.s

.PHONY : src/table.s

# target to generate assembly for a file
src/table.cpp.s:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/table.cpp.s
.PHONY : src/table.cpp.s

src/tuple.o: src/tuple.cpp.o

.PHONY : src/tuple.o

# target to build an object file
src/tuple.cpp.o:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/tuple.cpp.o
.PHONY : src/tuple.cpp.o

src/tuple.i: src/tuple.cpp.i

.PHONY : src/tuple.i

# target to preprocess a source file
src/tuple.cpp.i:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/tuple.cpp.i
.PHONY : src/tuple.cpp.i

src/tuple.s: src/tuple.cpp.s

.PHONY : src/tuple.s

# target to generate assembly for a file
src/tuple.cpp.s:
	$(MAKE) -f CMakeFiles/minisql.dir/build.make CMakeFiles/minisql.dir/src/tuple.cpp.s
.PHONY : src/tuple.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... package_source"
	@echo "... edit_cache"
	@echo "... NightlyMemCheck"
	@echo "... NightlyTest"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyMemoryCheck"
	@echo "... ExperimentalTest"
	@echo "... ContinuousUpdate"
	@echo "... NightlyUpdate"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalSubmit"
	@echo "... Experimental"
	@echo "... ContinuousCoverage"
	@echo "... ExperimentalConfigure"
	@echo "... Continuous"
	@echo "... Nightly"
	@echo "... NightlySubmit"
	@echo "... NightlyStart"
	@echo "... ExperimentalCoverage"
	@echo "... NightlyCoverage"
	@echo "... ExperimentalStart"
	@echo "... package"
	@echo "... NightlyBuild"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalUpdate"
	@echo "... ContinuousStart"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousTest"
	@echo "... ContinuousSubmit"
	@echo "... minisql"
	@echo "... src/API.o"
	@echo "... src/API.i"
	@echo "... src/API.s"
	@echo "... src/Block.o"
	@echo "... src/Block.i"
	@echo "... src/Block.s"
	@echo "... src/CatalogManager.o"
	@echo "... src/CatalogManager.i"
	@echo "... src/CatalogManager.s"
	@echo "... src/File.o"
	@echo "... src/File.i"
	@echo "... src/File.s"
	@echo "... src/IndexManager.o"
	@echo "... src/IndexManager.i"
	@echo "... src/IndexManager.s"
	@echo "... src/RecordManager.o"
	@echo "... src/RecordManager.i"
	@echo "... src/RecordManager.s"
	@echo "... src/buffermanager.o"
	@echo "... src/buffermanager.i"
	@echo "... src/buffermanager.s"
	@echo "... src/interpreter.o"
	@echo "... src/interpreter.i"
	@echo "... src/interpreter.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/table.o"
	@echo "... src/table.i"
	@echo "... src/table.s"
	@echo "... src/tuple.o"
	@echo "... src/tuple.i"
	@echo "... src/tuple.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

